services:
  recipes:
    build: .
    container_name: recipes
    networks:
      - jasper
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////data/recipes.db
    volumes:
      - ./data:/data

networks:
  jasper:
    external: true