services:
  recipes:
    build: .
    container_name: recipes
    networks:
      - jasper
    env_file:
      - .env
    environment:
      - DATAROOT=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  jasper:
    external: true
