"""Add oven_time column; make cook_time non-nullable

Revision ID: 2a3552bff9df
Revises: fd61f64e663c
Create Date: 2026-01-24 13:35:46.092215

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a3552bff9df"
down_revision = "fd61f64e663c"
branch_labels = None
depends_on = None


def upgrade():
    # Clean up any leftover temp table from failed batch operations (SQLite)
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_recipes")

    # Backfill existing NULL cook_time values to satisfy NOT NULL constraint
    op.execute("UPDATE recipes SET cook_time = 0 WHERE cook_time IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oven_time", sa.Integer(), nullable=True))
        batch_op.alter_column("cook_time", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.alter_column("cook_time", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column("oven_time")

    # ### end Alembic commands ###
