"""add moderation status

Revision ID: 4332bb8ecf71
Revises: c1d2e3f4a5b6
Create Date: 2026-07-01 11:02:51.401329

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4332bb8ecf71"
down_revision = "c1d2e3f4a5b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "moderation_status",
                sa.String(length=20),
                server_default="allowed",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "moderation_issues", sa.JSON(), server_default="[]", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("status_before_moderation", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("moderated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "moderation_notification_signature",
                sa.String(length=128),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_column("moderation_notification_signature")
        batch_op.drop_column("moderated_at")
        batch_op.drop_column("status_before_moderation")
        batch_op.drop_column("moderation_issues")
        batch_op.drop_column("moderation_status")

    # ### end Alembic commands ###
