"""Remove recipe machines

Revision ID: 83a2830f5168
Revises: 6d6db1c2e5f1
Create Date: 2026-06-11 17:33:59.409190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a2830f5168'
down_revision = '6d6db1c2e5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitchen_machines')
    op.drop_table('recipe_machines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_machines',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['kitchen_machines.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'machine_id')
    )
    op.create_table('kitchen_machines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
