"""Add recipe status and image_data fields

Revision ID: d2f8ee6cee38
Revises: a2b3c4d5e6f7
Create Date: 2026-04-14 12:56:34.350065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f8ee6cee38'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "user_machines" in inspector.get_table_names():
        op.drop_table("user_machines")
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='public', nullable=False))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')
        batch_op.drop_column('status')

    op.create_table('user_machines',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('machine_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['kitchen_machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'machine_id')
    )
    # ### end Alembic commands ###
